# Server
server.port=8080

# Datasource (MySQL) - change these to your DB
spring.datasource.url=jdbc:mysql://localhost:3306/findmyroomie
spring.datasource.username=root
spring.datasource.password=mypassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=9936da0a48f07a6ebb8621b4a221feb9
jwt.expirationMillis=900000
jwt.refreshExpirationMillis=604800000

# CORS
app.cors.allowed-origins=http://localhost:3000
